{
 "title": "System Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sysName", "label": "Device Name", "query": "sysName" }
  ]
 },
 "panels": [
  {
   "title": "System Name",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sysName{sysName=\"$sysName\"}"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime * ignoring(sysName) group_left(sysName) sysName{sysName=\"$sysName\"}/8640000"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg without(hrDeviceIndex)(hrProcessorLoad) * ignoring(hrDeviceIndex, sysName) group_left(sysName) sysName{sysName=\"$sysName\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex=\"1\"} * ignoring(hrStorageIndex, sysName) group_left(sysName) sysName{sysName=\"$sysName\"})\n/\n(hrStorageSize{hrStorageIndex=\"1\"} * ignoring(hrStorageIndex, sysName) group_left(sysName) sysName{sysName=\"$sysName\"})\n*100"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg without(hrDeviceIndex)(hrProcessorLoad) * ignoring(hrDeviceIndex, sysName) group_left(sysName) sysName{sysName=\"$sysName\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "hrStorageUsed{hrStorageIndex=\"1\"}* ignoring(hrStorageIndex, sysName) group_left(sysName) sysName{sysName=\"$sysName\"}",
     "legendFormat": "Storage Used"
    },
    {
     "expr": "hrStorageSize{hrStorageIndex=\"1\"}* ignoring(hrStorageIndex, sysName) group_left(sysName) sysName{sysName=\"$sysName\"}",
     "legendFormat": "Storage Size"
    }
   ]
  }
 ]
}