---
- hosts: dellos6
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "Gather Dell EMC OS6 Device Facts"
    dellos6_facts:
      gather_subset: ["all"] 
    register: facts

  - debug: var=facts
