---
- hosts: dellos10
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "Gather Dell EMC OS10 Device Facts"
    dellos10_facts:
      gather_subset: ["all"] 
    register: facts

  - debug: var=facts
