---
- hosts: dellos6
  connection: local
  gather_facts: no

  tasks:
  - name:
    dellos6_facts:
      gather_subset: ["all"] 
      provider: "{{ cli }}"
    register: facts

  - debug: var=facts









