---
- hosts: dellos9
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "Gather Dell EMC OS9 Device Facts"
    dellos9_facts:
      gather_subset: ["all"] 
    register: facts

  - debug: var=facts
