---
- hosts: dellos9
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "Set the hostname for the Dell EMC OS9 Device"
    dellos9_config:
      commands: ['hostname {{ hostname }}']
    register: set_hostname

  - debug: var=set_hostname
