---
- hosts: dellos9
  connection: local
  gather_facts: no

  tasks:
  - name: "Set the hostname for the Dell OS9 Device"
    dellos9_config:
      commands: ['hostname {{ hostname }}']
      provider: "{{ cli }}"

