---
- hosts: dellos6
  connection: local
  gather_facts: no

  tasks:
  - name: "Set the hostname for the Dell EMC OS6 Device"
    dellos6_config:
      commands: ['hostname {{ hostname }}']
      provider: "{{ cli }}"

