---
- hosts: dellos10
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "Get Dell EMC OS10 Show version"
    dellos10_command:
      commands: ['show version']
    register: show_ver

  - debug: var=show_ver









