---

vlan100_ip: 172.21.61.42/24
vlan200_ip: 172.21.66.42/24

tacacs_server_host_key_value: 52ea8aaeacbd28c45305b25629f46ac54c34e4c316e36ce7959393e696b0767f

vlt_backup_destination: 172.21.62.171
vlt_primary_priority: 2
vlt_mac: 00:00:00:00:00:02

#"wred mem" command exists only in rack1-leaf2
wred_mem: True

port_channel_id_1: 102

addtl_vlt_peers:
   port-channel 102:
      peer_lag: 102

addtl_interfaces:
   port-channel 102:
      desc: "To-Spines"
      admin: up
      mtu: "{{ mtu }}"

addtl_lag:
  port-channel 102:
     type: dynamic
     channel_members:
       - port: ethernet 1/1/9
         mode: "active"
       - port: ethernet 1/1/12
         mode: "active"

