---

vlan100_ip: 172.21.61.43/24
vlan200_ip: 172.21.66.43/24

tacacs_server_host_key_value: ce172944fe9d5199eb8b0431303c4201cdaa278c2d0063d8af75d22f196dff6f

vlt_backup_destination: 172.21.62.174
vlt_primary_priority: 1
vlt_mac: 00:00:00:00:00:03

port_channel_id_1: 101

addtl_vlt_peers:
   port-channel 101:
      peer_lag: 101

addtl_interfaces:
   port-channel 101:
      desc: "To-Spines"
      admin: up
      mtu: "{{ mtu }}"

addtl_lag:
  port-channel 101:
     type: dynamic
     channel_members:
       - port: ethernet 1/1/9
         mode: "active"
       - port: ethernet 1/1/12
         mode: "active"

