---

vlan100_ip: 172.21.61.41/24
vlan200_ip: 172.21.66.41/24

tacacs_server_host_key_value: 4378a617e994cbc448f7e956c81d25291f6b7a79ec927e39234db2c89c34502b

vlt_backup_destination: 172.21.62.172
vlt_primary_priority: 1
vlt_mac: 00:00:00:00:00:02

port_channel_id_1: 102

addtl_vlt_peers:
   port-channel 102: 
       peer_lag: 102

addtl_interfaces:
   port-channel 102:
      desc: "To-Spines"
      admin: up
      mtu: "{{ mtu }}"

addtl_lag:
  port-channel 102:
     type: dynamic
     channel_members:
       - port: ethernet 1/1/9
         mode: "active"
       - port: ethernet 1/1/12
         mode: "active"

#Overriding dellos_xstp from leaf.yaml. This leaf does not have 
#"spanning-tree port type edge" in port-channels 1-6
dellos_xstp:
    type: rstp

