---
- hosts: dellos9
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "Get Dell EMC OS9 Show version"
    dellos9_command:
      commands: ['show version']
    register: show_ver

  - debug: var=show_ver
