hostname: dellos10_sw1

# parameters for connection type local
cli:
  host: "{{ ansible_host }}"
  username: xxxxx
  password: xxxxx

# parametes for connection type network_cli
ansible_ssh_user: xxxxx
ansible_ssh_pass: xxxxx
ansible_network_os: dellos10

